# Generated by Django 5.2.17 on 2026-09-17 12:09

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=200)),
                ('nome_fantasia', models.CharField(blank=True, max_length=200)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('contato', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Peca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_interno', models.CharField(max_length=40, unique=True)),
                ('descricao', models.CharField(max_length=255)),
                ('garantia_dias', models.PositiveIntegerField(default=365)),
                ('garantia_km', models.PositiveIntegerField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('placa', models.CharField(blank=True, max_length=10)),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('casa', models.CharField(blank=True, max_length=80)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('perfil', models.CharField(choices=[('oficina', 'Oficina / Depósito'), ('compras', 'Compras'), ('manutencao', 'Manutenção'), ('direcao', 'Direção'), ('admin', 'Administrador')], default='oficina', max_length=20)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Garantia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('aberta', 'Aberta / laudo gerado'), ('enviada', 'Enviada ao fornecedor'), ('em_analise', 'Em análise'), ('procedente', 'Procedente'), ('improcedente', 'Improcedente'), ('cortesia', 'Cortesia comercial'), ('cancelada', 'Cancelada')], default='aberta', max_length=20)),
                ('data_compra', models.DateField(blank=True, null=True)),
                ('km_aplicacao', models.PositiveIntegerField(blank=True, null=True)),
                ('data_primeira_baixa', models.DateField(blank=True, null=True)),
                ('data_segunda_baixa', models.DateField(blank=True, null=True)),
                ('requisicao_anterior', models.CharField(blank=True, max_length=40)),
                ('requisicao_atual', models.CharField(blank=True, max_length=40)),
                ('data_envio', models.DateField(blank=True, null=True)),
                ('data_retorno', models.DateField(blank=True, null=True)),
                ('valor_peca', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('laudo_pdf', models.FileField(blank=True, null=True, upload_to='laudos/')),
                ('laudo_resumo', models.TextField(blank=True)),
                ('motivo_improcedente', models.TextField(blank=True)),
                ('nf_entrada_globo', models.CharField(blank=True, max_length=30)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='garantias_criadas', to=settings.AUTH_USER_MODEL)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.fornecedor')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='EventoGarantia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('status_anterior', models.CharField(blank=True, max_length=20)),
                ('status_novo', models.CharField(max_length=20)),
                ('descricao', models.TextField()),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='eventos/')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('garantia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='core.garantia')),
            ],
            options={
                'ordering': ['data'],
            },
        ),
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='anexos/')),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('enviado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('garantia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='core.garantia')),
            ],
        ),
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30)),
                ('serie', models.CharField(blank=True, max_length=10)),
                ('tipo', models.CharField(choices=[('compra', 'Compra / entrada original'), ('remessa', 'Saída para garantia'), ('retorno', 'Retorno do fornecedor'), ('entrada_procedente', 'Espelho Globo (procedente)')], max_length=30)),
                ('data_emissao', models.DateField()),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('chave_nfe', models.CharField(blank=True, max_length=44)),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='notas/')),
                ('observacao', models.TextField(blank=True)),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.fornecedor')),
            ],
            options={
                'unique_together': {('numero', 'serie', 'tipo')},
            },
        ),
        migrations.AddField(
            model_name='garantia',
            name='nota_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='garantias_compra', to='core.notafiscal'),
        ),
        migrations.AddField(
            model_name='garantia',
            name='nota_remessa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='garantias_remessa', to='core.notafiscal'),
        ),
        migrations.AddField(
            model_name='garantia',
            name='nota_retorno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='garantias_retorno', to='core.notafiscal'),
        ),
        migrations.AddField(
            model_name='garantia',
            name='peca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.peca'),
        ),
        migrations.AddField(
            model_name='garantia',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.veiculo'),
        ),
    ]
