# Generated by Django 5.2.17 on 2026-10-01 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='origem',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.CreateModel(
            name='HistoricoGarantiaMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(choices=[('REDENTOR', 'REDENTOR'), ('FUTURO', 'FUTURO'), ('BARRA G1', 'BARRA G1'), ('BARRA G2', 'BARRA G2')], max_length=20)),
                ('competencia', models.DateField(help_text='Primeiro dia do mes')),
                ('valor_concedido', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_em_analise', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_negado', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_solicitado', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('origem', models.CharField(default='planilha', max_length=20)),
                ('importado_em', models.DateTimeField(auto_now_add=True)),
                ('hash_linha', models.CharField(max_length=64, unique=True)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historico_mensal', to='core.fornecedor')),
            ],
            options={
                'ordering': ['-competencia', 'empresa', 'fornecedor_id'],
                'indexes': [models.Index(fields=['competencia'], name='core_histor_compete_bdb8e1_idx'), models.Index(fields=['empresa', 'competencia'], name='core_histor_empresa_f8145d_idx')],
            },
        ),
    ]
