# Generated by Django 5.2.17 on 2026-10-01 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_historico_planilha'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompraGlobus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(blank=True, max_length=80)),
                ('numero_nf', models.CharField(blank=True, max_length=30)),
                ('serie_nf', models.CharField(blank=True, max_length=10)),
                ('data_emissao', models.DateField(blank=True, null=True)),
                ('data_movto', models.DateField(blank=True, db_index=True, null=True)),
                ('peca_codigo', models.CharField(db_index=True, max_length=40)),
                ('peca_descricao', models.CharField(blank=True, max_length=255)),
                ('fornecedor_codigo', models.CharField(blank=True, max_length=40)),
                ('fornecedor_nome', models.CharField(blank=True, max_length=200)),
                ('quantidade', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('valor_unitario', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('chave_unica', models.CharField(max_length=64, unique=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Compra Globus (espelho)',
                'verbose_name_plural': 'Compras Globus (espelho)',
                'ordering': ['-data_movto'],
            },
        ),
        migrations.CreateModel(
            name='FornecedorGlobus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_forn', models.CharField(max_length=40, unique=True)),
                ('nome_fantasia', models.CharField(blank=True, max_length=200)),
                ('nr_forn', models.CharField(blank=True, max_length=40)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fornecedor Globus (espelho)',
                'verbose_name_plural': 'Fornecedores Globus (espelho)',
            },
        ),
        migrations.CreateModel(
            name='PecaGlobus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_interno', models.CharField(max_length=40, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('codigo_mat_int', models.CharField(blank=True, max_length=40)),
                ('codigo_grupo', models.CharField(blank=True, max_length=20)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Peca Globus (espelho)',
                'verbose_name_plural': 'Pecas Globus (espelho)',
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pecas', 'Pecas'), ('veiculos', 'Veiculos'), ('fornecedores', 'Fornecedores'), ('compras', 'Compras')], max_length=20)),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('erro', 'Erro')], max_length=10)),
                ('linhas_lidas', models.PositiveIntegerField(default=0)),
                ('linhas_gravadas', models.PositiveIntegerField(default=0)),
                ('erro', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-inicio'],
                'indexes': [models.Index(fields=['tipo', '-inicio'], name='core_synclo_tipo_91b4ed_idx')],
            },
        ),
        migrations.CreateModel(
            name='VeiculoGlobus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefixo', models.CharField(blank=True, max_length=30)),
                ('placa', models.CharField(blank=True, max_length=20)),
                ('codigo_veic_globus', models.CharField(max_length=40, unique=True)),
                ('codigo_empresa', models.CharField(blank=True, max_length=20)),
                ('condicao', models.CharField(blank=True, max_length=10)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Veiculo Globus (espelho)',
                'verbose_name_plural': 'Veiculos Globus (espelho)',
                'indexes': [models.Index(fields=['prefixo'], name='core_veicul_prefixo_e96432_idx'), models.Index(fields=['placa'], name='core_veicul_placa_e5f0c6_idx')],
            },
        ),
    ]
