# Generated by Django 5.2.17 on 2026-10-01 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_globus_espelho'),
    ]

    operations = [
        migrations.AddField(
            model_name='garantia',
            name='causa_improcedente',
            field=models.CharField(blank=True, choices=[('erro_aplicacao', 'Erro de aplicacao (mecanico/oficina)'), ('erro_operacao', 'Erro de operacao (motorista)'), ('falha_sistemica_veiculo', 'Falha sistemica do veiculo'), ('outro', 'Outro')], default='', max_length=40),
        ),
        migrations.AddField(
            model_name='garantia',
            name='cobranca_interna',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='garantia',
            name='compra_globus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='garantias', to='core.compraglobus'),
        ),
        migrations.AddField(
            model_name='garantia',
            name='data_aplicacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='garantia',
            name='data_fim_garantia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='garantia',
            name='nf_venda_data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='garantia',
            name='nf_venda_fornecedor',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='garantia',
            name='observacao_cobranca',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='garantia',
            name='prazo_garantia_dias',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='garantia',
            name='responsavel_nome',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='garantia',
            name='responsavel_tipo',
            field=models.CharField(blank=True, choices=[('oficina', 'Oficina'), ('mecanico', 'Mecanico'), ('motorista', 'Motorista'), ('sistema', 'Sistema'), ('outro', 'Outro')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='tipo',
            field=models.CharField(choices=[('pecas', 'Pecas'), ('veiculos', 'Veiculos'), ('fornecedores', 'Fornecedores'), ('compras', 'Compras'), ('saidas', 'Saidas')], max_length=20),
        ),
        migrations.CreateModel(
            name='AlertaReincidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veiculo_codigo', models.CharField(db_index=True, max_length=40)),
                ('peca_codigo', models.CharField(db_index=True, max_length=40)),
                ('peca_descricao', models.CharField(blank=True, max_length=255)),
                ('empresa', models.CharField(blank=True, max_length=80)),
                ('data_1', models.DateField()),
                ('data_2', models.DateField()),
                ('dias_entre', models.PositiveIntegerField()),
                ('fornecedor_1', models.CharField(blank=True, max_length=200)),
                ('nf_1', models.CharField(blank=True, max_length=30)),
                ('valor_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('status', models.CharField(choices=[('novo', 'Novo'), ('em_analise', 'Em analise'), ('garantia_aberta', 'Garantia aberta'), ('descartado', 'Descartado')], default='novo', max_length=20)),
                ('motivo_descarte', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-data_2', '-criado_em'],
                'constraints': [models.UniqueConstraint(fields=('veiculo_codigo', 'peca_codigo', 'data_2'), name='uniq_alerta_veiculo_peca_data2')],
            },
        ),
        migrations.AddField(
            model_name='garantia',
            name='alerta_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='garantias', to='core.alertareincidencia'),
        ),
        migrations.CreateModel(
            name='RegraPrazoGarantia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escopo', models.CharField(choices=[('peca', 'Peca'), ('grupo_peca', 'Grupo de peca'), ('fornecedor', 'Fornecedor'), ('tipo_servico', 'Tipo de servico')], max_length=20)),
                ('valor_escopo', models.CharField(max_length=80)),
                ('prazo_dias', models.PositiveIntegerField()),
                ('tipo_servico', models.CharField(choices=[('interno', 'Interno'), ('externo', 'Externo')], default='externo', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['escopo', 'valor_escopo'],
                'indexes': [models.Index(fields=['escopo', 'valor_escopo', 'ativo'], name='core_regrap_escopo_0bab1e_idx')],
            },
        ),
        migrations.CreateModel(
            name='SaidaGlobus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(blank=True, max_length=80)),
                ('veiculo_codigo', models.CharField(db_index=True, max_length=40)),
                ('peca_codigo', models.CharField(db_index=True, max_length=40)),
                ('peca_descricao', models.CharField(blank=True, max_length=255)),
                ('data_movto', models.DateField(blank=True, db_index=True, null=True)),
                ('tipo_his', models.CharField(blank=True, max_length=10)),
                ('numero_nf', models.CharField(blank=True, max_length=30)),
                ('fornecedor_codigo', models.CharField(blank=True, max_length=40)),
                ('fornecedor_nome', models.CharField(blank=True, max_length=200)),
                ('quantidade', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('valor_unitario', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('chave_unica', models.CharField(max_length=64, unique=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Saida Globus (espelho)',
                'verbose_name_plural': 'Saidas Globus (espelho)',
                'ordering': ['-data_movto'],
                'indexes': [models.Index(fields=['veiculo_codigo', 'peca_codigo', 'data_movto'], name='core_saidag_veiculo_e5897b_idx')],
            },
        ),
    ]
