SELECT
  CODIGOLOG NUMERO_LOG_SISTEMA,
  SISTEMA MÓDULO,
  USUARIO USUÁRIO_GLOBUS,
  OS_USER USUÁRIO_WINDOWS,
  TERMINAL COMPUTADOR_UTILIZADO,
  IP_ADRESS ENDEREÇO_COMPUTADOR_UTILIZADO,
  TO_CHAR(DATALOG, 'DD/MM/YYYY') DATA_DA_INTERVENÇÃO,
  TO_CHAR(HORALOG, 'HH24:MI:SS') HORA_DA_INTERVENÇÃO,
  TEXTOLOG DETALHES_DA_INTERVENÇÃO
--  CHECKSUMLOG,
--  USUARIOSAC
FROM
  CTR_LOG
WHERE
	(
	  		TEXTOLOG LIKE '%onstrutor%'
		OR
			TEXTOLOG LIKE '%onstrutot%'
	)
AND
  DATALOG BETWEEN TO_DATE('01/01/2024', 'DD/MM/YYYY') AND TO_DATE('02/10/2024', 'DD/MM/YYYY')
ORDER BY
  USUARIO,
  DATALOG