-- RECUPERA TODOS OS REGISTRIS DE USUÁRIOS QUE TEM ACESSO AO GLOBUS REPORT
SELECT USUARIO, NOMEUSUARIO, CODINTFUNC, ACESSOGLBREPORT FROM CTR_CADASTRODEUSUARIOS ORDER BY 4 DESC, 1;


-- RECUPERA TODOS OS USUÁRIOS QUE DE ALGUMA FORMA, POSSUEM ACESSO A ALGUM RELATÓRIO DO GLOBUS REPORT. NÃO É VERIFICAÇÃO DE PERMISSÃO DE ACESSO AO GLOBUS REPORT, E SIM ACESSO A RELATÓRIOS DENTRO DO MESMO, JÁ COM ACESSO A ELE.
SELECT	GRU.USUARIO FROM (SELECT DISTINCT(USUARIO) USUARIO FROM GRP_REPORT_USUARIOS) GRU INNER JOIN (SELECT USUARIO FROM CTR_CADASTRODEUSUARIOS WHERE ATIVO = 'S') CDU ON (GRU.USUARIO = CDU.USUARIO) ORDER BY 1

-- RECUPERA TODOS OS RELATÓRIOS ACESSADOS POR CADA USUÁRIO. NÃO É VERIFICAÇÃO DE PERMISSÃO DE ACESSO AO GLOBUS REPORT, E SIM ACESSO A RELATÓRIOS DENTRO DO MESMO, JÁ COM ACESSO A ELE.
SELECT GGR.DESCGRUPO "GRUPO DO GLOBUS REPORT", GRP.NOMEREPORT "NOME DO RELATÓRIO", GRU.USUARIO "NOME DO USUÁRIO", GRU.PERMISSAOSALVAR "PODE SALVAR RELATÓRIO" FROM (SELECT IDREPORT, USUARIO, PERMISSAOSALVAR FROM GRP_REPORT_USUARIOS WHERE USUARIO IN (SELECT USUARIO FROM CTR_CADASTRODEUSUARIOS WHERE ATIVO = 'S')) GRU INNER JOIN (SELECT IDREPORT, NOMEREPORT FROM GRP_REPORT) GRP ON (GRU.IDREPORT = GRP.IDREPORT) INNER JOIN (SELECT CODGRUPO, IDREPORT FROM GRP_REPORT_GRUPOS ) GRG ON ( GRU.IDREPORT = GRG.IDREPORT) INNER JOIN (SELECT CODGRUPO, DESCGRUPO FROM GRP_GRUPOS) GGR ON (GRG.CODGRUPO = GGR.CODGRUPO) ORDER BY 3,1,2


-- REMOVE TODOS OS PRIVILÉGIOS DE ACESSO DIFERENTE DO PADRÃO A TODOS OS USUÁRIOS QUE NÃO SEJAM OS LISTADOS
-- ACESSOGLBREPORT = 1 - SEM ACESSO
-- ACESSOGLBREPORT = 2 - ACESSO DESENVOLVEDOR
-- ACESSOGLBREPORT = 3 - ACESSO APENAS EXECUÇÃO
-- UPDATE CTR_CADASTRODEUSUARIOS SET ACESSOGLBREPORT = 3 WHERE CODINTFUNC NOT IN (3385, 18395, 19265, 19609, 38627) OR CODINTFUNC IS NULL;
-- UPDATE CTR_CADASTRODEUSUARIOS SET ACESSOGLBREPORT = 2 WHERE CODINTFUNC IN (3385, 18395, 19265, 19609, 38627);
--COMMIT;
--SELECT NOMEUSUARIO, ACESSOGLBREPORT  FROM CTR_CADASTRODEUSUARIOS ORDER BY 2 DESC
