SELECT
	'' AS "ID_FUNCIONARIO",
	TO_CHAR(TO_NUMBER(DCP.CPF)) AS CPF,
	'9'||TO_CHAR(TO_NUMBER(DCP.CPF)) AS "PIS",
	FNC.NOMECOMPLETOFUNC AS "NOME",
	FNC.CHAPAFUNC AS "MATRÍCULA",
	'' AS "FOLHA",
	DCT.CTPS||' SÉRIE: '||DCT.CTPS_SERIE AS "CTPS",
	DECODE(FNC.CODIGOEMPRESA, 1, 'VIAÇÃO REDENTOR LTDA', 2, 'TRANSPORTES FUTURO LTDA', 3, 'TRANSPORTES BARRA LTDA') AS "EMPRESA",
	DEP.DEPARTAMENTO,
	FUN.CARGO,
	'' AS "CENTRO DE CUSTO",
	'' AS "CÓDIGO DE BARRAS DO CRACHÁ",
	DRG.RG||' EMISSOR: '||DRG.EMISSOR_RG AS "RG",
	FNC.FONEFUNC AS "TELEFONE",
	'' AS "RAMAL",
	FNC.EMAILFUNC AS "EMAIL",
	'' AS "SENHA PARA ACESSO WEB",
	FNC.ENDRUAFUNC||', N.º '||FNC.ENDNRFUNC AS "ENDEREÇO",
	FNC.ENDBAIRROFUNC AS "BAIRRO",
	FNC.ENDCIDADEFUNC AS "CIDADE",
	'RJ' AS "UF",
	FNC.ENDCEPFUNC AS "CEP",
	TO_CHAR(FNC.DTADMFUNC, 'DD/MM/YYYY') AS "DATA DE ADMISSÃO",
	'' AS "NOME DO PAI",
	'' AS "NOME DA MÃE",
	TO_CHAR(FNC.DTNASCTOFUNC, 'DD/MM/YYYY') AS "DATA DE NASCIMENTO",
	NAC.NACIONALIDADE,
	FNC.LOCALNASTOFUNC AS "NATURALIDADE",
	'' AS "CRACHÁ",
	'' AS "CÓDIGO PARA USO NO REP",
	'' AS "SENHA PARA USO NO REP",
	'' AS "ADMINISTRADOR DO REP",
	'' AS "ATIVO",
	DECODE(FNC.SEXOFUNC, 'M', 'MASCULINO', 'F', 'FEMININO') AS "GÊNERO",
	DECODE(FNC.CODESTCIV, 1, 'SOLTEIRO(A)', 2, 'CASADO(A)', 3, 'UNIÃO ESTÁVEL', 4, 'DIVORCIADO(A)', 5, 'VIUVO(A)', 6, 'DESQUITADO(A)', 7, 'SEPARADO(A)') AS "ESTADO CIVIL",
	'' AS "PIN",
	'' AS "DATA INÍCIO BANCO HORAS",
	'S' AS "UTILIZA CERCA GEOGRÁFICA",
	'S' AS "TRABALHAR TODOS LOCAIS",
	'3' AS "MODO QUIOSQUE",
	'S' AS "HABILITA ACESSO MOBILE",
	'S' AS "HABILITA RECONHECIMENTO FACIAL",
	'S' AS "PERM MARC MOBILE ACESSO FUNC",
	'S' AS "PERM MARC MOBILE MODO QUIOSQUE",
	'N' AS "HABILITA MARCAÇÃO WEB",
	'S' AS "PERM ALTER/SOLIC ACESSO WEB",
	'S' AS "FOTO OBRIGATÓRIA NO MOBILE",
	'S' AS "FOTO OBRIG MARCAÇÃO WEB",
	'' AS "MENU INFORMAÇÕES GERAIS",
	'' AS "MENU PONTO DIÁRIO",
	'' AS "MENU MEU HISTÓRICO",
	'' AS "MENU MINH'' AS SOLICITAÇÕES",
	'' AS "MENU MODO QUIOSQUE",
	'' AS "FLUXO DE APROVAÇÃO",
	'' AS "HORÁRIO DE TRABALHO",
	'' AS "DATA INÍCIO HORÁRIO TRABALHO",
	'' AS "PERFIL DO FUNCIONÁRIO",
	'' AS "FUSO HORÁRIO",
	'' AS "MENU VISUALIZAR PONTO",
	'' AS "MENU ASSINAR PONTO",
	'' AS "MENU ESPELHO PONTO",
	'' AS "MENU COMPROVANTES",
	DCN.CNH AS "CNH",
	DCN.CATEGORIA_CNH AS "CATEGORIA DA CNH",
	DCN.VENCIMENTO_CNH AS "VENCIMENTO DA CNH",
	FCC.NOMESOCIAL AS "NOME SOCIAL",
	'' AS "DATA DE DEMISSÃO",
	'' AS "OBSERVAÇÕES"
FROM
	(SELECT * FROM FLP_FUNCIONARIOS WHERE CODIGOEMPRESA IN (1,2,3) AND DATATERMINOCONTRATO IS NULL AND SITUACAOFUNC <> 'D') FNC
LEFT OUTER JOIN
	(SELECT CODINTFUNC, NRDOCTO AS RG, RGEMISSORDOCTO EMISSOR_RG FROM FLP_DOCUMENTOS WHERE TIPODOCTO = 'RG') DRG ON (FNC.CODINTFUNC = DRG.CODINTFUNC)
LEFT OUTER JOIN
	(SELECT CODINTFUNC, NRDOCTO AS CNH, TO_CHAR(DTDOCTO,'DD/MM/YYYY') AS VENCIMENTO_CNH, CNHCATDOCTO AS CATEGORIA_CNH, CNHCIDADE AS CIDADE_CNH, CNHCODIGOUF AS UF_CNH FROM FLP_DOCUMENTOS WHERE TIPODOCTO = 'CNH') DCN ON (FNC.CODINTFUNC = DCN.CODINTFUNC)
LEFT OUTER JOIN
	(SELECT CODINTFUNC, NRDOCTO AS CPF FROM FLP_DOCUMENTOS WHERE TIPODOCTO = 'CPF') DCP ON (FNC.CODINTFUNC = DCP.CODINTFUNC)
LEFT OUTER JOIN
	(SELECT CODINTFUNC, NRDOCTO AS CTPS, CTPSSERIEDOCTO AS CTPS_SERIE FROM FLP_DOCUMENTOS WHERE TIPODOCTO = 'CTPS') DCT ON (FNC.CODINTFUNC = DCT.CODINTFUNC)
INNER JOIN
	(SELECT DISTINCT(HSL.CODINTFUNC) AS CODINTFUNC, HSL.CODSETOR, HSL.CODFUNCAO FROM FLP_HISTORICOSALARIAL HSL INNER JOIN (SELECT CODINTFUNC, MAX(DTHISTSAL) AS DTHISTSAL FROM FLP_HISTORICOSALARIAL WHERE CODAREA IN (1000, 1100, 1200, 1300, 1400, 4000) AND CODSETOR NOT IN (1100, 2050, 4050, 5050, 3501, 3502, 3503, 3504, 3505, 3506, 3050, 3509) GROUP BY CODINTFUNC) HSM ON (HSL.CODINTFUNC = HSM.CODINTFUNC AND HSL.DTHISTSAL = HSM.DTHISTSAL) WHERE  HSL.CODAREA IN (1000, 1100, 1200, 1300, 1400, 4000) AND HSL.CODSETOR NOT IN (1100, 2050, 4050, 5050, 3501, 3502, 3503, 3504, 3505, 3506, 3050, 3509)) HSL ON (FNC.CODINTFUNC = HSL.CODINTFUNC)
LEFT OUTER JOIN 
	(SELECT CODSETOR, DESCSETOR AS DEPARTAMENTO FROM FLP_SETOR) DEP ON (HSL.CODSETOR = DEP.CODSETOR)
LEFT OUTER JOIN
	(SELECT CODFUNCAO, DESCFUNCAOCOMPLETA AS CARGO FROM FLP_FUNCAO WHERE DESATIVADA = 'N') FUN ON (HSL.CODFUNCAO = FUN.CODFUNCAO)
LEFT OUTER JOIN
	(SELECT CODNAC, DESCNAC AS NACIONALIDADE FROM FLP_NACIONALIDADES) NAC ON (FNC.CODNAC = NAC.CODNAC)
LEFT OUTER JOIN
	(SELECT CODINTFUNC, NOMESOCIAL FROM FLP_FUNCIONARIOS_COMPLEMENTAR) FCC ON (FNC.CODINTFUNC = FCC.CODINTFUNC)
WHERE
	FNC.DTADMFUNC > TO_DATE(20/04/2024)
AND
	FNC.DATATERMINOCONTRATO IS NULL
AND
	FNC.CODIGOEMPRESA IN (1,2,3)
AND
	FNC.SITUACAOFUNC <> 'D'
ORDER BY
	FNC.NOMECOMPLETOFUNC
