SELECT
	A.COD_EMPRESA CODIGO_EMPRESA,
	DECODE(A.COD_EMPRESA,1,'VIA��O REDENTOR',2,'TRANSPORTES FUTURO',3,'TRANSPORTES BARRA') NOME_EMPRESA,
	TO_CHAR(A.DAT_PREST_CONTAS, 'DD/MM/YYYY') DATA_PRESTACAO_CONTAS,
	TO_CHAR(DAT_VIAGEM_GUIA, 'DD/MM/YYYY') DATA_VIAGEM,
	A.COD_GUIA GUIA,
	G.CODIGOLINHA LINHA,
	F.PREFIXOVEIC CARRO,
	PLACAATUALVEIC PLACA,
	H.CODFUNC MATRICULA_MOTORISTA,
	H.NOMEFUNC NOME_MOTORISTA,
	C.H_INI,
	C.H_FIM,
	I.CODFUNC MATRICULA_COBRADOR,
	I.NOMEFUNC NOME_COBRADOR,
	D.H_INI,
	D.H_FIM
FROM
	(SELECT DISTINCT(COD_SEQ_GUIA),COD_GUIA,COD_INTTURNO,DAT_PREST_CONTAS,DAT_VIAGEM_GUIA,COD_EMPRESA FROM GLOBUS.T_ARR_GUIA) A
	LEFT OUTER JOIN (SELECT DISTINCT(COD_SEQ_GUIA), CODINTLINHA FROM GLOBUS.T_ARR_DETALHE_GUIA ) B ON (A.COD_SEQ_GUIA = B.COD_SEQ_GUIA)
	LEFT OUTER JOIN (SELECT DISTINCT(COD_SEQ_GUIA), CODINTFUNC, FLG_MOT_COB,SUBSTR(TO_CHAR(HOR_FUNC_INI,'dd/mm/yyyy hh24:mi'),12,5) H_INI,SUBSTR(TO_CHAR(HOR_FUNC_FIM,'dd/mm/yyyy hh24:mi'),12,5) H_FIM FROM GLOBUS.T_ARR_TROCAS_FUNC WHERE FLG_MOT_COB = 'M') C ON (B.COD_SEQ_GUIA = C.COD_SEQ_GUIA)
	LEFT OUTER JOIN (SELECT DISTINCT(COD_SEQ_GUIA), CODINTFUNC, FLG_MOT_COB,SUBSTR(TO_CHAR(HOR_FUNC_INI,'dd/mm/yyyy hh24:mi'),12,5) H_INI,SUBSTR(TO_CHAR(HOR_FUNC_FIM,'dd/mm/yyyy hh24:mi'),12,5) H_FIM FROM GLOBUS.T_ARR_TROCAS_FUNC WHERE FLG_MOT_COB = 'C') D ON (C.COD_SEQ_GUIA = D.COD_SEQ_GUIA)
	LEFT OUTER JOIN (SELECT DISTINCT(COD_SEQ_GUIA), CODIGOVEIC FROM GLOBUS.T_ARR_DET_VIAG_A_VIAG) E ON (A.COD_SEQ_GUIA = E.COD_SEQ_GUIA)
	LEFT OUTER JOIN (SELECT CODIGOVEIC, PREFIXOVEIC, PLACAATUALVEIC FROM GLOBUS.FRT_CADVEICULOS )F ON (E.CODIGOVEIC = F.CODIGOVEIC)
	LEFT OUTER JOIN (SELECT CODINTLINHA, CODIGOLINHA, NOMELINHA FROM GLOBUS.BGM_CADLINHAS) G ON (B.CODINTLINHA = G.CODINTLINHA)
	LEFT OUTER JOIN (SELECT CODINTFUNC, CODFUNC, NOMEFUNC FROM GLOBUS.FLP_FUNCIONARIOS) H ON (C.CODINTFUNC = H.CODINTFUNC)
	LEFT OUTER JOIN (SELECT CODINTFUNC, CODFUNC, NOMEFUNC FROM GLOBUS.FLP_FUNCIONARIOS) I ON (D.CODINTFUNC = I.CODINTFUNC)
WHERE
	-- N�MERO DA EMPRESA QUE SE DESEJA PESQUISAR
	A.COD_EMPRESA = 2
AND
	-- N�MERO DA EMPRESA QUE SE DESEJA PESQUISAR
	A.COD_GUIA = '19072013360'
AND
	-- DATA DESEJADA
	A.DAT_VIAGEM_GUIA = TO_DATE('19/07/2013', 'DD/MM/YYYY') 
AND
	-- LINHA
	G.CODIGOLINHA = '753'
AND
	-- PLACA
	PLACAATUALVEIC = 'KQX-0785'
AND
	-- MATRICULA DO MOTORISTA
	H.CODFUNC = '022262'
AND
	-- NOME DO MOTORISTA
	H.NOMEFUNC LIKE '%ISAQUE%' 
AND
	-- MATRICULA DO COBRADOR
	I.CODFUNC = '055440'
AND
	-- NOME DO COBRADOR
	I.NOMEFUNC LIKE '%IVANI%' 
ORDER BY
	A.DAT_VIAGEM_GUIA,
	H.CODFUNC,
	I.CODFUNC,
	G.CODIGOLINHA,
	F.PREFIXOVEIC






-----------------------------------------------------------------
-------SCRIPT EM RODAP� NO ARQUIVO ORIGINAL - N�O ALTERADO-------
-----------------------------------------------------------------
--SELECT
--	A.COD_GUIA GUIA
--FROM
--	(SELECT DISTINCT(COD_SEQ_GUIA),COD_GUIA,COD_INTTURNO,DAT_PREST_CONTAS,DAT_VIAGEM_GUIA,COD_EMPRESA FROM GLOBUS.T_ARR_GUIA) A,
--	(SELECT DISTINCT(COD_SEQ_GUIA), CODINTLINHA FROM GLOBUS.T_ARR_DETALHE_GUIA ) B,
--	(SELECT DISTINCT(COD_SEQ_GUIA), CODINTFUNC, FLG_MOT_COB FROM GLOBUS.T_ARR_TROCAS_FUNC WHERE FLG_MOT_COB = 'M') C,
--	(SELECT DISTINCT(COD_SEQ_GUIA), CODINTFUNC, FLG_MOT_COB FROM GLOBUS.T_ARR_TROCAS_FUNC WHERE FLG_MOT_COB = 'C') D,
--	(SELECT DISTINCT(COD_SEQ_GUIA), CODIGOVEIC FROM GLOBUS.T_ARR_DET_VIAG_A_VIAG) E,
--	(SELECT CODIGOVEIC, PREFIXOVEIC, PLACAATUALVEIC FROM GLOBUS.FRT_CADVEICULOS )F,
--	(SELECT CODINTLINHA, CODIGOLINHA, NOMELINHA FROM GLOBUS.BGM_CADLINHAS) G,
--	(SELECT CODINTFUNC, CODFUNC, NOMEFUNC FROM GLOBUS.FLP_FUNCIONARIOS) H,
--	(SELECT CODINTFUNC, CODFUNC, NOMEFUNC FROM GLOBUS.FLP_FUNCIONARIOS) I
--WHERE
--	A.COD_SEQ_GUIA=B.COD_SEQ_GUIA
--AND
--	B.COD_SEQ_GUIA=C.COD_SEQ_GUIA
--AND
--	C.COD_SEQ_GUIA=D.COD_SEQ_GUIA
--AND
--	A.COD_SEQ_GUIA=E.COD_SEQ_GUIA
--AND
--	E.CODIGOVEIC=F.CODIGOVEIC
--AND
--	B.CODINTLINHA=G.CODINTLINHA
--AND
--	C.CODINTFUNC=H.CODINTFUNC
--AND
--	D.CODINTFUNC=I.CODINTFUNC
--AND
--	A.COD_EMPRESA = '2'
--AND
--	A.DAT_VIAGEM_GUIA = TO_DATE('19/07/2013', 'DD/MM/YYYY')
--AND
--	G.CODIGOLINHA = '465'
--AND
--	PLACAATUALVEIC = 'LRX-4918'
--ORDER BY
--	A.DAT_VIAGEM_GUIA,
--	H.CODFUNC,
--	I.CODFUNC,
--	G.CODIGOLINHA,
--	F.PREFIXOVEIC
-----------------------------------------------------------------
-------SCRIPT EM RODAP� NO ARQUIVO ORIGINAL - N�O ALTERADO-------
-----------------------------------------------------------------