SELECT
	CIC.NRCOTA NÚMERO_DA_COTAÇÃO,
	CIC.CODIGOMATINT CÓDIGO_INTERNO_DO_MATERIAL,
	ECM.DESCRICAOMAT DESCIÇÃO_DO_MATERIAL,
	ECM.DESCRICAOABREVMAT DESCIÇÃO_ABREV_DO_MATERIAL,
	CIC.NUMEROSOLIC NÚMERO_DA_SOLICITAÇÃO,
	CIC.NUMEROPEDIDO NÚMERO_DO_PEDIDO,
	CIC.OBSITENSCOTMAT OBSERVAÇÃO_JUSTIFIC_FECHAMENTO
FROM
	CPR_ITENSCOTADOS CIC
	INNER JOIN (SELECT CODIGOMATINT, DESCRICAOMAT, DESCRICAOABREVMAT FROM EST_CADMATERIAL) ECM ON CIC.CODIGOMATINT = ECM.CODIGOMATINT
WHERE
	CIC.NRCOTA IN (99768)
AND
	CIC.OBSITENSCOTMAT IS NOT NULL
ORDER BY
	CIC.NRCOTA,
	CIC.OBSITENSCOTMAT ASC