SELECT
	USUARIO "Usuário",
	SISTEMA "Módulo do Globus",
	INDICEMENU "Índice do Menu",
	CAPTION "Menu",
	TEMDIREITOEXCLUSAOMENU "Exclusão",
	TEMDIREITOINCLUSAOMENU "Inclusão",
	TEMDIREITOALTERACAOMENU "Alteração"
FROM
	CTR_MENUSAOUSUARIO
ORDER BY
	1,
	2,
	3
