SELECT
  'EMPRESA'||';'||
  'CARRO'||';'||
  'PLACA'||';'||
  'MATRÍCULA'||';'||
  'MOTORISTA'||';'||
  'MULTA'||';'||
  'MUNICÍPIO'||';'||
  'CÓDIGO ÓRGÃO'||';'||
  'ÓRGÃO'||';'||
  'LOCAL DA INFRAÇÃO'||';'||
  'INFRAÇÃO'||';'||
  'PONTUAÇÃO DA INFRAÇÃO'||';'||
  'DATA E HORA DA MULTA'||';'||
  'DATA DE VENCIMENTO'||';'||
  'DATA LIMITE CONDUTOR'||';'||
  'VALOR' MULTAS
FROM
  DVS_MULTA
WHERE
  ROWNUM < 2
UNION ALL
SELECT
  DECODE(FNC.CODIGOEMPRESA,
    1, 'VIAÇÃO REDENTOR',
    2, 'TRANSPORTES FUTURO',
    3, 'TRANSPORTES BARRA',
    100, 'TRANSPORTES FUTURO',
    101, 'TRANSPORTES FUTURO',
    102, 'TRANSPORTE BARRA',
    200, 'TRANSPORTE BARRA',
    201, 'VIAÇÃO REDENTOR',
    202, 'TRANSPORTE FUTURO',
    301, 'VIAÇÃO REDENTOR',
    302, 'TRANSPORTE FUTURO',
    303, 'TRANSPORTE BARRA',
    888, 'TRANSPORTES BARRA',
    998, 'VIAÇÃO REDENTOR',
    999, 'TRANSPORTES FUTURO')||';'||
  CDV.PREFIXOVEIC||';'||
  CDV.PLACAATUALVEIC||';'||
  FNC.CODFUNC||';'||
  FNC.NOMEFUNC||';'||
  MLT.NUMEROAIMULTA||';'||
  MUN.DESCMUNIC||';'||
  MLT.CODIGOORG||';'||
  ORG.DESCRICAOORG||';'||
  MLT.LOCALMULTA||';'||
  INF.DESCRICAOINFRA||';'||
  INF.PONTUACAOINFRA||';'||
  MLT.DATAHORAMULTA||';'||
  MLT.DATAVECTOMULTA||';'||
  MLT.DATALIMITECONDUTOR||';'||
  MLT.VALORMULTA MULTAS
FROM
  (SELECT NUMEROAIMULTA, CODIGOVEIC, CODMUNIC, CODINTFUNC, CODIGOORG, LOCALMULTA, CODIGOINFRA, DATAHORAMULTA, TO_CHAR(DATAVECTOMULTA, 'DD/MM/YYYY') DATAVECTOMULTA, TO_CHAR(DATALIMITECONDUTOR, 'DD/MM/YYYY') DATALIMITECONDUTOR, VALORMULTA FROM DVS_MULTA WHERE DATAHORAMULTA BETWEEN :DAT1 AND :DAT2) MLT
  LEFT OUTER JOIN (SELECT CODIGOEMPRESA, CODIGOVEIC, PREFIXOVEIC, PLACAATUALVEIC FROM FRT_CADVEICULOS WHERE CODIGOEMPRESA IS NOT NULL AND CODIGOEMPRESA <> 0 AND CODIGOEMPRESA IN (1,2,3,100,101,102,200,201,202,301,302,303,888,998,999)) CDV ON (MLT.CODIGOVEIC = CDV.CODIGOVEIC)
  LEFT OUTER JOIN (SELECT CODIGOORG, DESCRICAOORG FROM DVS_ORGAO) ORG ON (MLT.CODIGOORG = ORG.CODIGOORG)
  INNER JOIN (SELECT CODIGOEMPRESA, CODFUNC, CODINTFUNC, NOMEFUNC FROM VW_FUNCIONARIOS) FNC ON (MLT.CODINTFUNC = FNC.CODINTFUNC)
  LEFT OUTER JOIN (SELECT CODIGOINFRA, DESCRICAOINFRA, PONTUACAOINFRA FROM DVS_INFRACAO) INF ON (MLT.CODIGOINFRA = INF.CODIGOINFRA)
  LEFT OUTER JOIN (SELECT CODMUNIC, DESCMUNIC FROM DVS_MUNICIPIO) MUN ON (MLT.CODMUNIC = MUN.CODMUNIC)
WHERE
  MLT.DATAHORAMULTA BETWEEN :DAT1 AND :DAT2
AND
  CDV.CODIGOEMPRESA IS NOT NULL
AND
  CDV.CODIGOEMPRESA <> 0
AND
  CDV.CODIGOEMPRESA IN (1,2,3,100,101,102,200,201,202,301,302,303,888,998,999)
ORDER BY
  1
