SELECT
	DISTINCT(CODTPDOC) AS CODTPDOC,
	DESCTPDOC AS "DESCRIÇÃO DO TIPO DE DOCUMENTO"
FROM
	CPRTPDOC
WHERE
	CODTPDOC IN ('001', 'CTE', 'NCE', 'NDS', 'NEA', 'NEC', 'NEG', 'NES', 'NF', 'NFC', 'NFE', 'NFF', 'NFG', 'NFP', 'NFS', 'NSA', 'NSP', 'NVS')
AND
	DESCTPDOC IN ('CONHECIMENTO TRANSP ELETRONICO', 'CONHECIMENTO DE TRANSPORTE', 'NOTA CARIOCA DE SERVIÇO', 'NOTAS DE SAIDAS', 'NOTA ELETRONICA AVULSA', 'NOTA ELETRONICA CARIOCA', 'NOTA ELETRONICA DE GARANTIA', 'NOTA ELETRONICA DE SERVIÇO', 'NOTA FISCAL', 'NOTA FISCAL DE CONSUMIDOR ELET', 'NOTA FISCAL ELETRONICA', 'NOTA FISCAL FATURA', 'NOTA FISCAL DE GARANTIA', 'N.F. LANC FORA LIVRO FISCAL', 'NOTA FISCAL DE SERVICO', 'NOTA DE SERVIÇO A VISTA', 'NOTA FISCAL SEM PEDIDO', 'NOTA A VISTA', 'NOTA FISCAL DE GARANTIA')
ORDER BY
	1